### ISSUE TITLE
Please fix the forEach discouraging rule: for .. of can't be used to iterate with index.

### ISSUE THREAD

**Issue by ldeluigi** [github/eslint-plugin-github#115]
Please fix this rule: for .. of can't be used to iterate with index.

_Originally posted by @ldeluigi in https://github.com/github/eslint-plugin-github/issues/86#issuecomment-751358559_

**Comment by alfaproject** [comment]
Yes it can:
```js
for (const [i, item] of ['a', 'b', 'c'].entries()) {
  console.log(i, item);
}
```

**Comment by ldeluigi** [comment]
Ty
