### ISSUE TITLE
Package requirements link in README is broken

### ISSUE THREAD

**Issue by Arcanemagus** [github/eslint-plugin-github#14]
The "Package Requirements" link in the readme is broken, looks like it's trying to link to [here](https://github.com/github/eslint-plugin-github/blob/master/docs/package-requirements.md), but is instead linking to `https://github.com/github/eslint-plugin-github/blob/master/github/eslint-plugin-github/blob/master/docs/package-requirements.md`

**Comment by josh** [comment]
Thanks! should be fixed now. The github relative linking stuff didn't work as I expected.
