### ISSUE TITLE
Add support for flat config

### ISSUE THREAD

**Issue by TheElegantCoding** [github/eslint-plugin-github#513]
Please add support for ESLint 9, including Flat config support.

See:

- https://eslint.org/docs/latest/use/configure/configuration-files-new
- https://eslint.org/blog/2022/08/new-config-system-part-1/
- https://eslint.org/blog/2022/08/new-config-system-part-2/
- https://eslint.org/docs/latest/use/configure/migration-guide

Thanks!

**Comment by TheElegantCoding** [comment]
also to consider, in typescript there is no types for the exported package 
![image](https://github.com/github/eslint-plugin-github/assets/70770072/81f09217-246d-462e-9750-8fa932e96316)

**Comment by TheElegantCoding** [comment]
The new version works well in my config the only error is the type declaration needed for ts configs

**Comment by arelia** [comment]
Flat config support added in https://github.com/github/eslint-plugin-github/releases/tag/v5.1.0
