### ISSUE TITLE
Add support for eslint 9

### ISSUE THREAD

**Issue by lukasoppermann** [github/eslint-plugin-github#539]
Hey,

this plugin seems to be incompatible with eslint 9 and thus blocks us from upgrading our projects.

It would be great to bring it up to eslint 9 and enable flat config support #513

**Comment by silverwind** [comment]
Was this fixed? At least according to package.json, it's compatible:

https://github.com/github/eslint-plugin-github/blob/abcfc3bdfb4628c75fcbdca1b6fae1fa82cddb1c/package.json#L60

**Comment by turadg** [comment]
Looks like this was a dupe of
- https://github.com/github/eslint-plugin-github/issues/513

which was closed by

- https://github.com/github/eslint-plugin-github/pull/571

**Comment by WtfJoke** [comment]
Yeah it seems to be fixed, because https://github.com/github/eslint-plugin-github/issues/513 is closed and the readme got an entry for flatconfig (eslint9) [here](https://github.com/github/eslint-plugin-github?tab=readme-ov-file#flat-configuration-eslint-configjs)
