### ISSUE TITLE
ESLint v9+ still uses the unsupported filenames plugin in the recommended extension

### ISSUE THREAD

**Issue by prince-chrismc** [github/eslint-plugin-github#580]
thank for the work on updating this , I saw #578 but I think there's at least one more reference to the plugin the recommended section 
https://github.com/github/eslint-plugin-github/blob/7c07c177361a08fe4b9c53f55309623aad09176b/lib/configs/recommended.js#L21

```
export default [{
    files: [
        "src/**/*.ts",
        "__tests__/**/*.ts",
    ],
    ignores: [
        "**/dist/",
        "**/lib/",
        "**/node_modules/",
        "**/jest.config.js",
    ],
}, ...compat.extends("plugin:github/recommended"), {
    plugins: {
        "@typescript-eslint": typescriptEslint,
    },

    languageOptions: {
        globals: {
            ...globals.node,
        },

        parser: tsParser,
        ecmaVersion: 2023,
        sourceType: "module",

        parserOptions: {
            project: "./tsconfig.json",
        },
    },
```

**Comment by gracepark** [comment]
What version are you on? We recently updated so that with ESLint v9 we brought the filenames rule into our plugin. But on legacy config we use the original filenames plugin.

**Comment by prince-chrismc** [comment]
I am using the latest [5.1.3](https://github.com/prince-chrismc/check-actor-permissions-action/commit/8849790ba8eb36c2a3d71e168c4f2d0908e6c84b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R44)

~I am not a javascript developer but I did follow the eslint migration and believe I am using the new format for the config files.~ I just saw #539 which update the documentation. Follow that I was able to get it working :)

Cheers!
