### ISSUE TITLE
Possibly `github/filenames-match-regex` or docs are incorrect

### ISSUE THREAD

**Issue by lukasoppermann** [github/eslint-plugin-github#582]
Hey,
really awesome that work has started again and it is now eslint9 compatible. ❤ 

I think the `github/filenames-match-regex` rules is either wrong or the docs are incorrect.

In the docs (https://github.com/github/eslint-plugin-github/blob/main/docs/rules/filenames-match-regex.md) it is stated that the correct naming convention is `camelCase`:

> 👍 Examples of correct code for this rule:
>
> fileName.js

The default regex also looks like camleCase: https://github.com/github/eslint-plugin-github/blob/main/lib/rules/filenames-match-regex.js#L28

However, if I use `'github/filenames-match-regex': 'error',` I get an eslint error (wrong name for e.g. `toCamelCase.ts`)

I have to use this for it to work: `'github/filenames-match-regex': ['error', '^([a-z0-9]+)([A-Z][a-z0-9]+)*(.[a-z0-9-]+)?$'],`.

Am I doing something wrong?

**Comment by gracepark** [comment]
@lukasoppermann - Hi! So I essentially just took the same default from the original filenames plugin:

https://github.com/selaux/eslint-plugin-filenames/blob/32fc70dd7572211d1e5b97e06ec7a005c77fe8d4/lib/rules/match-regex.js#L18

I didn't want to change anything, but let me take a further look!

**Comment by gracepark** [comment]
Oh ok I get it now - so the default does not allow multiple humps in camelCase - just one.  So while `camelCase.js` will work, `camelCaseTest.js` will not. I think for now we'll stick with the original to keep business as usual for this rule - I'll update the docs however because I think it's fair to assume numerous humps would be ok.

**Comment by gracepark** [comment]
Note has been updated: https://github.com/github/eslint-plugin-github/blob/main/README.md 

I'll close this for now, if you run into anything feel free to open.

**Comment by lukasoppermann** [comment]
NIce @gracepark, I think this needs to be updated as well: https://github.com/github/eslint-plugin-github/blob/main/docs/rules/filenames-match-regex.md

At least to my understanding (let me know if I am wrong), `camelCase` does not require only 2-word names.

So this would also need to be updated.

I am not the best at regex, but [this rule](https://github.com/github/eslint-plugin-github/blob/main/lib/rules/filenames-match-regex.js#L28) does look like it should allow multiple humps. 😕 
`/^([a-z0-9]+)([A-Z][a-z0-9]+)*$/g` <- the asterisk (`*`) behind `([A-Z][a-z0-9]+)*` means this can repeat 0-∞ times, right? In don't get why it fails

**Comment by gracepark** [comment]
Hm, can you try: 

`'github/filenames-match-regex': ['error', '^([a-z0-9]+)([A-Z][a-z0-9]+)*$'],`
 
Let me know if that doesn't work for you. 

Sidenote, I realized it's not the humps that's causing an issue, it's that the github recommended config wants a different naming convention: `^[a-z0-9-]+(.[a-z0-9-]+)?$` while the filenames original plugin had camelCase as the default. I need to update the default here and the docs (I'll update the README and the rules markdown). Thank you so much for bringing this to my attention!

**Comment by lukasoppermann** [comment]
> Hm, can you try:
> 'github/filenames-match-regex': ['error', '^([a-z0-9]+)([A-Z][a-z0-9]+)*$'],

I did add this in my config, and it works this way.

> Sidenote, I realized it's not the humps that's causing an issue, it's that the github recommended config wants a different naming convention: ^[a-z0-9-]+(.[a-z0-9-]+)?$ while the filenames original plugin had camelCase as the default. I need to update the default here and the docs (I'll update the README and the rules markdown). Thank you so much for bringing this to my attention!

This makes sense, awesome. 👍
